# Generated by Django 4.0.3 on 2022-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=122)),
                ('credit_author', models.CharField(max_length=122, null=True)),
                ('email_author', models.EmailField(max_length=254, null=True)),
                ('content_title', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=512)),
                ('date', models.DateField()),
            ],
        ),
    ]
