# Generated by Django 4.0.3 on 2022-04-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissons',
            name='content_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submissons',
            name='credit_author',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='submissons',
            name='email_author',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
